### ISSUE TITLE
required = true and type = choice issue when only Coding.display is available

### ISSUE THREAD

**Issue by JohannesOehm** [NUMde/compass-numapp-web#11]
**Describe the bug**
![grafik](https://user-images.githubusercontent.com/16564576/134340771-8966ada5-4931-43aa-9d3c-c2b77b90e3ee.png)

Even though I selected something, I cannot continue. I guess, this is because the answerOptions only element is `Coding.display`. But e.g. the LHC-Formbuilder emits list of options just like that if no terminology is used to code answerOptions, so I guess this is the official way by the FHIR standard.

**To Reproduce**
Try the following file (i had to change this extension to .txt to be able to upload it with this commit):
[S0000_Well-being and COVID-19.txt](https://github.com/NUMde/compass-numapp-web/files/7210518/S0000_Well-being.and.COVID-19.txt)

**Expected behavior**
After I have choosen an element, I could hit the "Fortfahren" button.

**Comment by jonathan-reisdorf** [comment]
While I would personally pick valueString answer options in such a case, for the sake of compatibility, I'll add a PR for the fallback feature :+1:
