### ISSUE TITLE
Discussion: Format of encrypted payload

### ISSUE THREAD

**Issue by JohannesOehm** [NUMde/compass-numapp-web#3]
Currently, the IBM native app uses the following object structure for the encrypted data: 

```
{
 type: "questionnaire_response",
 data: {
  subjectId: "7bfc3b07-a97d-4e11-8ac6-b970c1745476",
  body: "{\"resourceType\": \"QuestionnaireResponse\"}"
 }
}
```

while the Data4Life web app uses:

```
{
 type: "questionnaire_response",
 data: {
  subjectId: "7bfc3b07-a97d-4e11-8ac6-b970c1745476",
  body: {"resourceType": "QuestionnaireResponse"}
 }
}
```
`

As you can see, data.body is a string in case of the IBM app, while the Data4Life app directly inserts the FHIR as JSON object. 

I want to point out that it would be good to define a common behaviour here. Any opinions on this?

**Comment by TimWalz** [comment]
Hi @JohannesOehm ,
thank you for raising this topic.
We suggest to continue using the plain JSON object, specifically in the JSON context that we are already in at that point, rather than json-encoding the information and putting then a string into JSON.
